---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: compress dir into home/log.zip
    archive:
      path: /var/log/
      dest: /home/noc/log.tar.gz
      owner: noc
      group: noc
      format: gz

  - name: Fetch the log file to the local filesystem
    fetch: 
      src: /home/noc/log.tar.gz
      dest: logbackup-{{ inventory_hostname }}.tar.gz
      flat: yes
