---
- hosts: all
  become: yes
  gather_facts: no

  tasks: 
    - name: install at
      action: yum name=at state=installed

    - name: enable and start service
      service:
        name: atd
        enabled: yes
        state: started



