---
           
- hosts: kafka
  become: yes
  serial: 1
  tasks:
    - name: install Java
      yum: name=java-11-openjdk.x86_64 state=latest

    - name: check java version
      command: 
        cmd: java -version
      register: JavaVersion

    - name: show java version installed
      debug: 
        msg: "java version is {{JavaVersion}}"   

    - name: disable RAM swap
      command:
        cmd: swapoff -a

    - name: modify fstab
      replace: 
        path: /etc/fstab
        regexp: '^/swapfile'
        replace: '#/swapfile'  
        backup: yes

- hosts: kafka
  become: yes
  roles:
    - kafka   