---
- hosts: kafka
  serial: 1
  tasks:
    - name: modify /etc/hosts file
      lineinfile:
        line: "{{ ansible_default_ipv4.address }} zookeeper{{ broker_id }}\n{{ ansible_default_ipv4.address }} kafka{{ broker_id }}"
        dest: /tmp/hosts 
        create: true     
      delegate_to: localhost 
           
- hosts: kafka
  become: yes
  serial: 1
  tasks:
    - name: install Java
      yum: name=openjdk-11-jdk state=latest

    - name: check java version
      command: 
        cmd: java -version
      register: JavaVersion

    - name: show java version installed
      debug: 
        msg: "java version is {{JavaVersion}}"   

    - name: disable RAM swap
      command:
        cmd: swapoff -a

    - name: modify fstab
      replace: 
        path: /etc/fstab
        regexp: '^/swapfile'
        replace: '#/swapfile'  
        backup: yes

- hosts: kafka
  become: yes
  become_user: root
  roles:
    - kafka   
    
- hosts: nifi
  become: yes
  roles:
    - nifi       