---
- hosts: localhost
  become: yes
  tasks:
  - name: download  http://apps.l33t.com/transaction_list /home/ansible/transaction_list
    block:
      - get_url:
          url: http://apps.l34t.com/transaction_list
          dest: /home/ansible/transaction_list
        register: geturl_var
      - debug:
          msg: 'File downloaded."{{ geturl_var }}" '

      - replace:
          dest: /home/ansible/transaction_list
          regexp: '#BLANKLINE'
          replace: '\n'
        register: repvar
      - debug:
          msg: 'the replacement went "{{ repvar }}"'

    rescue:
      - debug:
          msg: 'l33t.com appears to be down. Try again later."{{ geturl_var }}"'
    always:
      - debug:
          msg: 'Attempt Completed "{{ geturl_var }}"'

#  - name: configure to replace all #BLANKLINE with \n
#    replace:
#      dest: /home/ansible/transaction_list
#      regexp: '#BLANKLINE'
#      replace: '\n'
#    register: repvar
#  - debug: 
#      msg: 'the replacement went "{{ repvar }}"'   
