---
           
- hosts: kafka
#  become: yes
  serial: 1
  tasks:
    - name: 1-create hosts file with kafka/zoo def
      lineinfile:
        line: "{{ ansible_default_ipv4.address }} zookeeper{{ broker_id }}"
        dest: /tmp/hosts 
        create: true     
      delegate_to: localhost  

    #- name: copy remote hosts file to local
    #  fetch: 
    #    src: /etc/hosts
    #    dest: "{{inventory_hostname}}/hosts"
    #    flat: yes

    - name: 2-copy remote
      lineinfile:
        dest: /etc/hosts
        line: "{{item}}"
      with_lines: cat /tmp/hosts  

    - name: create zookeeper file-- it should create 1 number per file host
      template:
        src: roles/kafka/templates/myid.j2
        dest: /data/zookeeper/myid
