---
- hosts: all_server
  become: yes
  serial: 1
  roles:
    - baseline
- name: task execution oriz
  hosts: all_server
  order: inventory
  serial: 1
  tasks:
    - name: install httpd
      yum: name=httpd state=latest
- name: task execution parallel
  hosts: all_server 
  tasks:    
    - name: start and enable httpd
      service: name=httpd state=started enabled=yes
