---
# tasks file for test-role-1
   - name: install python
     yum:
       name: python
       state: present

   - name: install httpd
     yum:
       name: httpd
       state: present

   - name: start httpd
     service:
        name: httpd
        state: started
