- name: check if kafka is already installed--dobt work
  shell: /opt/kafka/bin/kafka-topics.sh --version | awk '{ print $1 }'
  register: KafkaVersion  
  ignore_errors: True
- debug: var=KafkaVersion

- block:   
   - name: download package
     get_url: 
       url: https://archive.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz
       dest: /opt

   - name: untar package
     unarchive:
      src: /opt/kafka_2.12-2.2.0.tgz
      dest: /opt/
      remote_src: yes
   
   - name: rename kafka directory
     command:
      cmd: mv /opt/kafka_2.12-2.2.0 /opt/kafka
     ignore_errors: yes

   - name: remove old directory
     file:
       path: /opt/kafka_2.12-2.2.0.tgz
       state: absent
     ignore_errors: yes 

  when: KafkaVersion !='2.2.0'

#- name: copy kafka
#  copy: 
#    src: kafka
##    dest: /etc/init.d/kafka
##    owner: root 
##    mode: u=rxw,g=r,o=r

#- name: update kafka
#  shell: 'chkconfig --add /etc/init.d/kafka'

- name: create kafka directory
  file:
    path: /data/kafka
    state: directory

- name: remove server.properties file
  file:
    path: /opt/kafka/config/server.properties
    state: absent    

- name: kafka configuration file    
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
      
#- name: modify /etc/hosts
#  lineinfile:
#    path: /etc/hosts
#    #line: "172.31.127.194  kafka1 \n172.31.127.194  zookeeper1 \n172.31.123.189  kafka2 \n172.31.123.189  zookeper2 \n172.31.126.225  kafka3 \n172.31.126.225  zookeeper3"
#    line: "{{ansible_default_ipv4.address}}  kafka1 \n172.31.127.194  zookeeper1 \n172.31.123.189  kafka2 \n172.31.123.189  zookeper2 \n172.31.126.225  kafka3 \n172.31.126.225  zookeeper3"
#    state: present 

- name: copy remote
  lineinfile:
    dest: /etc/hosts
    line: "{{item}}"
  with_lines: cat /tmp/hosts  

- name: Create the logs Directory and myid File for the Zookeeper Service
  file: 
    path: /data/zookeeper
    state: directory
 
- name: create zookeeper file-- it should create 1 number per file host
  template:
    src: myid.j2
    dest: /data/zookeeper/myid

- name: Create the zookeeper.properties File
  copy:
    src: zookeeper.properties
    dest: /opt/kafka/config/zookeeper.properties
   
#- name: start kafka
#  service:
#    name: kafka
#    state: started