- name: check if kafka is already installed
  shell: /opt/kafka/bin/kafka-topics.sh --version
  register: KafkaVersion  
  ignore_errors: True

- block:   
   - name: download package
     get_url: 
       url: https://archive.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz
       dest: /opt
   - name: untar package
     unarchive:
      src: /opt/kafka_2.12-2.2.0.tgz
      dest: /opt/    
      remote_src: yes
   - name: rename kafka directory
     command:
      cmd: mv /opt/kafka_2.12-2.2.0 /opt/kafka
     ignore_errors: yes
   - name: remove old directory
     file:
       path: /opt/kafka_2.12-2.2.0.tgz
       state: absent
     ignore_errors: yes 

  when: KafkaVersion is not defined   


- name: copy kafka
  copy: 
    src: kafka
    dest: /etc/init.d/kafka
    owner: root 
    mode: u=rxw,g=r,o=r

- name: update kafka
  shell: 'chkconfig --add /etc/init.d/kafka'

- name: create kafka directory
  file:
    path: /data/kafka
    state: directory

- name: kafka configuration file    
  template:
    src: server.properties
    dest: /opt/kafka/config/

      
- name: modify /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "172.31.127.194 kafka1 \n 172.31.127.194  zookeeper \n  172.31.123.189 kafka 2 \n 172.31.123.189  zookeper2 \n 172.31.126.225  kafka3 \n 172.31.126.225  zookeeper3"

- name: Create the logs Directory and myid File for the Zookeeper Service
  file: 
    path: /data/zookeeper
    state: directory
 
- name: create zookeeper file
  lineinfile:
    path: /data/zookeeper/myid
    line: "1\n2\n3\n"
    state: present
    create: true

- name: Create the zookeeper.properties File
  copy:
    src: zookeeper.properties
    dest: /opt/kafka/config/zookeeper.properties
   
- name: start kafka
  service:
    name: kafka
    state: started