- name: check if kafka is already installed
  shell: /opt/kafka/bin/kafka-topics.sh --version
  register: KafkaVersion  

#- name: copy zookeper
#  copy: 
#    src: zookeeper
#    dest: /etc/init.d/zookeeper
#    owner: root 

#- name: update rc.d
#  shell: 'chkconfig --add /etc/init.d/zookeeper'
#
#- name: start zookeeper
#  service:
#    name: zookeeper
#    state: started
#
- name: copy kafka
  copy: 
    src: kafka
    dest: /etc/init.d/kafka
    owner: root 

- name: update kafka
  shell: 'chkconfig --add /etc/init.d/kafka'

- name: start kafka
  service:
    name: kafka
    state: started

- name: create kafka directory
  file:
    path: /data/kafka
    state: directory

- name: kafka configuration file    
  template:
    src: server.properties
    dest: /opt/kafka/config/

- block:   
   - name: download package
     get_url: 
       url: https://archive.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz
       dest: /opt
   - name: untar package
     unarchive:
      src: /opt/kafka_2.12-2.2.0.tgz
      dest: /opt/    
      remote_src: yes
   - name: rename kafka directory
     command:
      cmd: mv /opt/kafka_2.12-2.2.0 /opt/kafka
     ignore_errors: yes
   - name: remove old directory
     file:
       path: /opt/kafka_2.12-2.2.0.tgz
       state: absent
     ignore_errors: yes 

  when: KafkaVersion is not defined   