---
- hosts: localhost
  become: yes
  tasks: 
  - name: create a file
    block:
      - file:
          name: /mnt/newfile
          state: touch
    rescue:
      - name: output of file from rescue
        debug:
          msg: "Unable to create secret file"
